name       : vinagre
version    : 3.18.1
release    : 2
homepage   : https://wiki.gnome.org/Apps/Vinagre
source     :
    - http://ftp.gnome.org/pub/gnome/sources/vinagre/3.18/vinagre-3.18.1.tar.xz : 5ddad95bb4dacc771d57541ecad49c9c9879043c0404c726c4853a243d710c98
license    : GPL-3.0
summary    : Vinagre is a remote desktop viewer for GNOME.
description: |
    Vinagre is a remote desktop viewer for GNOME.
builddeps  :
    - pkgconfig(libsecret-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(telepathy-glib)
    - pkgconfig(vte-2.91)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(freerdp)
    - itstool
setup      : |
    # TODO: Enable avahi and spice
    %configure --with-ssh --enable-rdp
build      : |
    %make
install    : |
    %make_install
