name       : vinagre
version    : 3.16.1
release    : 1
homepage   : https://wiki.gnome.org/Apps/Vinagre
source     :
    - http://ftp.gnome.org/pub/gnome/sources/vinagre/3.16/vinagre-3.16.1.tar.xz : d77c0057e8525efeef8b35839bce07e5451d99f3ef9d156c7f549a4c1ad6483f
license    : GPL-3.0
summary    : Vinagre is a remote desktop viewer for GNOME.
description: |
    Vinagre is a remote desktop viewer for GNOME.
clang      : no
builddeps  :
    - pkgconfig(libsecret-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(telepathy-glib)
    - pkgconfig(vte-2.91)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(freerdp)
    - itstool
setup      : |
    # TODO: Enable avahi and spice
    %configure --with-ssh --enable-rdp
build      : |
    %make
install    : |
    %make_install
