name       : vinagre
version    : 3.22.0
release    : 18
homepage   : https://wiki.gnome.org/Apps/Vinagre
source     :
    - git|https://gitlab.gnome.org/GNOME/vinagre.git : cdcddc15b36b0a2d772f33e43e6e6b3f6c9ec837
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Vinagre is a remote desktop viewer for GNOME.
description: |
    Vinagre is a remote desktop viewer for GNOME.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(freerdp2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(telepathy-glib)
    - pkgconfig(vte-2.91)
    - gnome-common
    - itstool
    - vala
    - yelp-tools
setup      : |
    NOCONFIGURE=1 ./autogen.sh
    %configure --enable-rdp --enable-spice --with-ssh --enable-compile-warnings=minimum
build      : |
    %make
install    : |
    %make_install
