name       : vinagre
version    : 3.20.2
release    : 6
homepage   : https://wiki.gnome.org/Apps/Vinagre
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/vinagre/3.20/vinagre-3.20.2.tar.xz : 5fc78ef9ab9ee7d4e3c50d38d82d9bcbd915191bcf0349d55a2fd56eaa87eaa0
license    : GPL-3.0
summary    : Vinagre is a remote desktop viewer for GNOME.
description: |
    Vinagre is a remote desktop viewer for GNOME.
builddeps  :
    - pkgconfig(libsecret-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(telepathy-glib)
    - pkgconfig(vte-2.91)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(freerdp)
    - itstool
    - vala
setup      : |
    # TODO: Enable avahi and spice
    %configure --with-ssh --enable-rdp
build      : |
    %make
install    : |
    %make_install
