name       : vinagre
version    : 3.22.0
release    : 21
homepage   : https://wiki.gnome.org/Apps/Vinagre
source     :
    - git|https://gitlab.gnome.org/GNOME/vinagre.git : 9da43e8505c91c9938abd88c2253da339a9c5ff4
license    : GPL-3.0-or-later
component  : desktop.gnome
summary    : Vinagre is a remote desktop viewer for GNOME.
description: |
    Vinagre is a remote desktop viewer for GNOME.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(freerdp2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(telepathy-glib)
    - pkgconfig(vte-2.91)
    - gnome-common
    - itstool
    - vala
    - yelp-tools
setup      : |
    %patch -p1 < $pkgfiles/Fix-compilation-with-GCC-10.patch
    NOCONFIGURE=1 ./autogen.sh
    %configure --enable-rdp --enable-spice --with-ssh --enable-compile-warnings=minimum
build      : |
    %make
install    : |
    %make_install
