name       : vinagre
version    : 3.22.0
release    : 7
homepage   : https://wiki.gnome.org/Apps/Vinagre
source     :
    - http://ftp.gnome.org/pub/gnome/sources/vinagre/3.22/vinagre-3.22.0.tar.xz : cd1cdbacca25c8d1debf847455155ee798c3e67a20903df8b228d4ece5505e82
license    : GPL-3.0
component  : desktop.gnome
summary    : Vinagre is a remote desktop viewer for GNOME.
description: |
    Vinagre is a remote desktop viewer for GNOME.
builddeps  :
    - pkgconfig(freerdp)
    - pkgconfig(libsecret-1)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(spice-client-gtk-3.0)
    - pkgconfig(telepathy-glib)
    - pkgconfig(vte-2.91)
    - itstool
    - vala
setup      : |
    # TODO: Enable avahi
    %configure --with-ssh --enable-rdp
build      : |
    %make
install    : |
    %make_install
