name       : vinagre
version    : 3.18.2
release    : 5
homepage   : https://wiki.gnome.org/Apps/Vinagre
source     :
    - http://ftp.gnome.org/pub/gnome/sources/vinagre/3.18/vinagre-3.18.2.tar.xz : 65b81299de0b75a9433e5654d5314f347895d5efb7acd3b111e5e8c03f48fbc4
license    : GPL-3.0
summary    : Vinagre is a remote desktop viewer for GNOME.
description: |
    Vinagre is a remote desktop viewer for GNOME.
builddeps  :
    - pkgconfig(libsecret-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(telepathy-glib)
    - pkgconfig(vte-2.91)
    - pkgconfig(gtk-vnc-2.0)
    - pkgconfig(freerdp)
    - itstool
    - vala
setup      : |
    # TODO: Enable avahi and spice
    %configure --with-ssh --enable-rdp
build      : |
    %make
install    : |
    %make_install
